server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jinmaodong/cloud2020learn.git
          search-paths:
            - file-config-center/springcloud/
          skip-ssl-validation: true
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
