server:
  port: 8003
eureka:
  instance:
    instance-id: hystrixprovider8003
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: CLOUD-HYSTRIX-PROVIDER-SERVICE
